services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - furia-challenge-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: furia_db

volumes:
  furia-challenge-data:
